@startuml
left to right direction
actor "Actor" as actor1
actor "Actor" as actor2
rectangle {
"Caso de uso" as (1)
"Caso de uso" as (2)
"Caso de uso" as (3)
}
actor1 -- 1
actor1 -- 2
actor1 -- 3
actor2 -- 1
actor2 -- 3
@enduml